apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: weather
    tier: backend
spec:
  ports:
  - port: 9000
    targetPort: 8080
  selector:
    app: weather
    tier: backend
