apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: weather
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: weather
    tier: backend
