apiVersion: v1
kind: ReplicationController
metadata:
  name: backend-contr
  labels:
    app: weather
    tier: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
        tier: backend
    spec:
      containers:
      - name: server
        image: io89/weatherapp_backend
        command: ["docker run -p 8080:8080 weatherapp_backend"]
        args: ["8080"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
