apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: weather
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: weather
    tier: backend
