apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: weather
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: weather
    tier: frontend
