apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-contr
  labels:
    app: weather
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
        tier: frontend
    spec:
      containers:
      - name: front
        image: io89/weatherapp_front
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

