apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: weather
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: weather
    tier: frontend
